# Generated by Django 3.0.3 on 2020-02-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField()),
                ('ISBN', models.CharField(max_length=13)),
                ('page_count', models.IntegerField()),
                ('cover_link', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=3)),
            ],
        ),
    ]
