# Generated by Django 3.0.3 on 2020-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_auto_20200228_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
