# Generated by Django 3.0.3 on 2020-03-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20200302_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
